### ISSUE TITLE
Caliptra_Integration_Specification.pdf is corrupt

### ISSUE THREAD

**Issue by korran** [chipsalliance/caliptra-rtl#67]
After  https://github.com/chipsalliance/caliptra-rtl/commit/2041ef1811096b50bf715705678c18ea97d6d801, the text in the flowcharts on page 21 of [Caliptra_Integration_Specification.pdf](https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/Caliptra_Integration_Specification.pdf) is no longer visible.

**Comment by anjpar** [comment]
Fixed in #88 . Closing issue.

**Comment by korran** [comment]
I don't think this is fixed; I still see missing text in the figures in https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/Caliptra_Integration_Specification.pdf :

![Screenshot from 2023-06-26 16-17-01](https://github.com/chipsalliance/caliptra-rtl/assets/993854/be48c0d3-11c0-49de-946a-08bfd97509ae)

**Comment by bharatpillilli** [comment]
@anjpar - I am also still seeing some pictures corrupted...can we plz do an quick turnaround PR with the doc updated?

**Comment by anjpar** [comment]
Fixed.
